package com.testinium.runners;


import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;
import org.junit.runner.RunWith;

/**
 * Failed Test Re-execution Runner for the Testinium Selenium/Cucumber test automation framework.
 * 
 * <p>This runner class is designed to re-execute only previously failing scenarios from a prior
 * test run. It serves as a critical component for regression testing, flaky test triage, and
 * CI/CD retry mechanisms. Rather than running the entire test suite again, this runner targets
 * specifically the scenarios that failed in a previous execution.</p>
 * 
 * <h2>Purpose and Workflow</h2>
 * <p>The typical workflow for using this runner is:</p>
 * <ol>
 *   <li>Execute the primary test suite using {@link CukesRunner}, which generates a
 *       {@code target/rerun.txt} file containing the URIs and line numbers of all failed scenarios</li>
 *   <li>Run this {@code FailedTestRunner} to re-execute only those failing scenarios</li>
 *   <li>Analyze results to determine if failures were genuine bugs or transient/flaky issues</li>
 * </ol>
 * 
 * <h2>Configuration Details</h2>
 * <p>The {@link CucumberOptions} annotation configures this runner with the following parameters:</p>
 * <ul>
 *   <li><strong>features = "@target/rerun.txt"</strong>: The leading {@code @} character is a
 *       Cucumber convention indicating an <em>indirection file</em>. Instead of specifying feature
 *       file paths directly, this tells Cucumber to read the {@code target/rerun.txt} file, which
 *       contains feature URIs and line numbers (e.g., {@code src/main/resources/features/login.feature:15})
 *       of the scenarios to re-run. This file is generated by the {@code rerun} plugin configured
 *       in {@link CukesRunner}.</li>
 *   <li><strong>glue = "com/testinium/step_definitions"</strong>: Specifies the package containing
 *       step definition classes and lifecycle hooks. This must match the glue configuration in
 *       {@link CukesRunner} to ensure consistent step resolution when replaying failures.</li>
 * </ul>
 * 
 * <h2>Dependency on CukesRunner</h2>
 * <p>This runner depends on a prior execution of {@link CukesRunner} (or another runner configured
 * with the {@code rerun:target/rerun.txt} plugin) to generate the rerun file. The {@link CukesRunner}
 * class includes the plugin configuration {@code "rerun:target/rerun.txt"} which outputs the
 * locations of all failed scenarios during test execution.</p>
 * 
 * <h2>Behavior Notes</h2>
 * <ul>
 *   <li>If {@code target/rerun.txt} does not exist, is empty, or contains invalid content, this
 *       runner's behavior depends on the Cucumber version:
 *       <ul>
 *         <li>It may run zero scenarios (empty test suite) if the file is empty or missing</li>
 *         <li>It may throw an error if the file contains malformed URIs</li>
 *       </ul>
 *   </li>
 *   <li>No reporting plugins are configured by default; extend this class or use Maven Surefire
 *       configuration to add reporting if needed</li>
 * </ul>
 * 
 * <h2>Usage Context</h2>
 * <p>This runner is typically used for:</p>
 * <ul>
 *   <li><strong>Flaky Test Triage</strong>: Re-running failures to identify intermittent issues</li>
 *   <li><strong>Local Debugging</strong>: Quickly re-executing failed scenarios during development</li>
 *   <li><strong>CI Retry Mechanisms</strong>: Automated retry of failed tests in CI/CD pipelines</li>
 *   <li><strong>Regression Verification</strong>: Confirming bug fixes by re-running specific failures</li>
 * </ul>
 * 
 * <h2>JUnit Integration</h2>
 * <p>The {@code @RunWith(Cucumber.class)} annotation delegates the JUnit 4 test lifecycle to
 * Cucumber's JUnit integration. This allows the runner to be executed using standard JUnit
 * tooling (IDE test runners, Maven Surefire plugin, etc.) while Cucumber handles the actual
 * BDD test execution.</p>
 * 
 * <h2>Example Execution</h2>
 * <pre>{@code
 * # Run primary test suite first (generates rerun.txt)
 * mvn test -Dtest=CukesRunner
 * 
 * # Then re-run only failures
 * mvn test -Dtest=FailedTestRunner
 * }</pre>
 * 
 * @see CukesRunner The primary test runner that generates the rerun.txt input file
 * @see com.testinium.step_definitions Step definition classes providing glue code for scenario execution
 * @see io.cucumber.junit.Cucumber Cucumber's JUnit 4 runner implementation
 * @see io.cucumber.junit.CucumberOptions Configuration annotation for Cucumber runtime behavior
 * 
 * @since 1.0
 */
@RunWith(Cucumber.class)
@CucumberOptions(
        glue = "com/testinium/step_definitions",
        features = "@target/rerun.txt"
)
public class FailedTestRunner {

}
